import type { Project, Todo, TaskLog } from './types';

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'web-dashboard',
    path: 'C:/Projects/web-dashboard',
    default_branch: 'main',
    created_at: '2026-03-20T09:00:00Z',
    updated_at: '2026-03-24T14:30:00Z',
  },
  {
    id: 'proj-2',
    name: 'api-server',
    path: 'C:/Projects/api-server',
    default_branch: 'develop',
    created_at: '2026-03-18T11:00:00Z',
    updated_at: '2026-03-23T18:00:00Z',
  },
];

export const mockTodos: Todo[] = [
  // Project 1 todos
  {
    id: 'todo-1',
    project_id: 'proj-1',
    title: 'Add user authentication flow',
    description: 'Implement login/signup pages with JWT token management. Include form validation and error handling.',
    status: 'completed',
    priority: 1,
    branch_name: 'feat/auth-flow',
    worktree_path: 'C:/Projects/web-dashboard/.worktrees/feat-auth-flow',
    created_at: '2026-03-20T10:00:00Z',
    updated_at: '2026-03-21T15:00:00Z',
  },
  {
    id: 'todo-2',
    project_id: 'proj-1',
    title: 'Create dashboard charts component',
    description: 'Build reusable chart components using recharts. Support bar, line, and pie charts with responsive layout.',
    status: 'running',
    priority: 2,
    branch_name: 'feat/dashboard-charts',
    worktree_path: 'C:/Projects/web-dashboard/.worktrees/feat-dashboard-charts',
    created_at: '2026-03-21T09:00:00Z',
    updated_at: '2026-03-24T14:30:00Z',
  },
  {
    id: 'todo-3',
    project_id: 'proj-1',
    title: 'Fix responsive layout on mobile',
    description: 'The sidebar overlaps main content on screens smaller than 768px. Fix CSS grid layout and add proper breakpoints.',
    status: 'pending',
    priority: 3,
    branch_name: null,
    worktree_path: null,
    created_at: '2026-03-22T11:00:00Z',
    updated_at: '2026-03-22T11:00:00Z',
  },
  {
    id: 'todo-4',
    project_id: 'proj-1',
    title: 'Add dark mode toggle',
    description: 'Implement theme switching with localStorage persistence. Update all components to support dark/light variants.',
    status: 'failed',
    priority: 4,
    branch_name: 'feat/dark-mode',
    worktree_path: 'C:/Projects/web-dashboard/.worktrees/feat-dark-mode',
    created_at: '2026-03-23T08:00:00Z',
    updated_at: '2026-03-23T12:00:00Z',
  },
  // Project 2 todos
  {
    id: 'todo-5',
    project_id: 'proj-2',
    title: 'Implement rate limiting middleware',
    description: 'Add express-rate-limit with Redis store. Configure different limits for auth vs API endpoints.',
    status: 'completed',
    priority: 1,
    branch_name: 'feat/rate-limiting',
    worktree_path: 'C:/Projects/api-server/.worktrees/feat-rate-limiting',
    created_at: '2026-03-18T12:00:00Z',
    updated_at: '2026-03-19T16:00:00Z',
  },
  {
    id: 'todo-6',
    project_id: 'proj-2',
    title: 'Add WebSocket event handlers',
    description: 'Set up WebSocket server with room management. Implement real-time notification broadcasting.',
    status: 'running',
    priority: 2,
    branch_name: 'feat/websocket',
    worktree_path: 'C:/Projects/api-server/.worktrees/feat-websocket',
    created_at: '2026-03-20T10:00:00Z',
    updated_at: '2026-03-24T10:00:00Z',
  },
  {
    id: 'todo-7',
    project_id: 'proj-2',
    title: 'Write integration tests for /users endpoints',
    description: 'Add supertest-based integration tests covering CRUD operations, validation errors, and auth checks.',
    status: 'stopped',
    priority: 3,
    branch_name: 'test/users-integration',
    worktree_path: 'C:/Projects/api-server/.worktrees/test-users-integration',
    created_at: '2026-03-21T14:00:00Z',
    updated_at: '2026-03-22T09:00:00Z',
  },
];

export const mockLogs: TaskLog[] = [
  // Logs for todo-2 (running)
  {
    id: 'log-1',
    todo_id: 'todo-2',
    log_type: 'info',
    message: 'Starting Claude CLI instance...',
    created_at: '2026-03-24T14:00:00Z',
  },
  {
    id: 'log-2',
    todo_id: 'todo-2',
    log_type: 'info',
    message: 'Worktree created at C:/Projects/web-dashboard/.worktrees/feat-dashboard-charts',
    created_at: '2026-03-24T14:00:05Z',
  },
  {
    id: 'log-3',
    todo_id: 'todo-2',
    log_type: 'output',
    message: 'Analyzing project structure and existing chart components...',
    created_at: '2026-03-24T14:01:00Z',
  },
  {
    id: 'log-4',
    todo_id: 'todo-2',
    log_type: 'output',
    message: 'Creating BarChart component with responsive container...',
    created_at: '2026-03-24T14:05:00Z',
  },
  {
    id: 'log-5',
    todo_id: 'todo-2',
    log_type: 'commit',
    message: 'feat: add BarChart component with tooltip and legend support',
    created_at: '2026-03-24T14:10:00Z',
  },
  {
    id: 'log-6',
    todo_id: 'todo-2',
    log_type: 'output',
    message: 'Creating LineChart component with axis configuration...',
    created_at: '2026-03-24T14:15:00Z',
  },
  {
    id: 'log-7',
    todo_id: 'todo-2',
    log_type: 'commit',
    message: 'feat: add LineChart component with customizable axes',
    created_at: '2026-03-24T14:20:00Z',
  },
  {
    id: 'log-8',
    todo_id: 'todo-2',
    log_type: 'output',
    message: 'Working on PieChart component...',
    created_at: '2026-03-24T14:25:00Z',
  },
  // Logs for todo-4 (failed)
  {
    id: 'log-9',
    todo_id: 'todo-4',
    log_type: 'info',
    message: 'Starting Claude CLI instance...',
    created_at: '2026-03-23T08:30:00Z',
  },
  {
    id: 'log-10',
    todo_id: 'todo-4',
    log_type: 'output',
    message: 'Implementing CSS custom properties for theme variables...',
    created_at: '2026-03-23T09:00:00Z',
  },
  {
    id: 'log-11',
    todo_id: 'todo-4',
    log_type: 'error',
    message: 'Error: TypeScript compilation failed - Cannot find module \'@/theme/colors\'',
    created_at: '2026-03-23T10:00:00Z',
  },
  {
    id: 'log-12',
    todo_id: 'todo-4',
    log_type: 'error',
    message: 'Claude CLI process exited with code 1',
    created_at: '2026-03-23T10:01:00Z',
  },
  // Logs for todo-6 (running)
  {
    id: 'log-13',
    todo_id: 'todo-6',
    log_type: 'info',
    message: 'Starting Claude CLI instance...',
    created_at: '2026-03-24T10:00:00Z',
  },
  {
    id: 'log-14',
    todo_id: 'todo-6',
    log_type: 'output',
    message: 'Setting up WebSocket server with ws library...',
    created_at: '2026-03-24T10:05:00Z',
  },
  {
    id: 'log-15',
    todo_id: 'todo-6',
    log_type: 'commit',
    message: 'feat: initialize WebSocket server with connection handling',
    created_at: '2026-03-24T10:15:00Z',
  },
  {
    id: 'log-16',
    todo_id: 'todo-6',
    log_type: 'output',
    message: 'Implementing room join/leave logic with broadcast...',
    created_at: '2026-03-24T10:20:00Z',
  },
];
