import type { ClientPluginManifest } from '../types';
import JiraPanel from '../../components/JiraPanel';
import JiraSettings from './JiraSettings';

export const jiraClientPlugin: ClientPluginManifest = {
  id: 'jira',
  displayName: 'Jira',
  displayNameKo: 'Jira',
  PanelComponent: JiraPanel,
  SettingsComponent: JiraSettings,
  hasTab: true,
  isEnabled: (project) => !!project.jira_enabled,
  translations: {
    en: {
      'tabs.jira': 'Jira',
      'jira.title': 'Jira Issues',
      'jira.search': 'Search issues...',
      'jira.allStatuses': 'All Statuses',
      'jira.refresh': 'Refresh',
      'jira.import': 'Import as Task',
      'jira.importing': 'Importing...',
      'jira.imported': 'Imported!',
      'jira.noIssues': 'No issues found',
      'jira.noIssuesHint': 'Try changing the filter or search query.',
      'jira.loadMore': 'Load More',
      'jira.total': 'total',
      'jira.transition': 'Change Status',
      'jira.comment': 'Comment',
      'jira.commentPlaceholder': 'Add a comment...',
      'jira.commentSend': 'Send',
      'jira.createIssue': 'Create Issue',
      'jira.createSummary': 'Summary',
      'jira.createDesc': 'Description',
      'jira.createType': 'Issue Type',
      'jira.creating': 'Creating...',
      'jira.notConfigured': 'Jira is not configured. Enable it in project settings.',
      'jira.assignee': 'Assignee',
      'jira.unassigned': 'Unassigned',
      'jira.updated': 'Updated',
      'header.jiraTitle': 'Jira Integration',
      'header.jiraBaseUrl': 'Jira URL',
      'header.jiraBaseUrlPlaceholder': 'https://your-domain.atlassian.net',
      'header.jiraProjectKey': 'Project Key',
      'header.jiraProjectKeyPlaceholder': 'e.g. PROJ',
      'header.jiraEmail': 'Email',
      'header.jiraEmailPlaceholder': 'your@email.com',
      'header.jiraApiToken': 'API Token',
      'header.jiraApiTokenPlaceholder': 'Jira API token',
      'header.jiraTestConnection': 'Test Connection',
      'header.jiraTesting': 'Testing...',
      'header.jiraConnected': 'Connected!',
      'header.jiraFailed': 'Connection failed',
      'header.jiraTokenHint': 'Create a token at id.atlassian.com/manage-profile/security/api-tokens',
    },
    ko: {
      'tabs.jira': 'Jira',
      'jira.title': 'Jira 이슈',
      'jira.search': '이슈 검색...',
      'jira.allStatuses': '모든 상태',
      'jira.refresh': '새로고침',
      'jira.import': '작업으로 가져오기',
      'jira.importing': '가져오는 중...',
      'jira.imported': '가져옴!',
      'jira.noIssues': '이슈가 없습니다',
      'jira.noIssuesHint': '필터나 검색어를 변경해보세요.',
      'jira.loadMore': '더 보기',
      'jira.total': '건',
      'jira.transition': '상태 변경',
      'jira.comment': '댓글',
      'jira.commentPlaceholder': '댓글 입력...',
      'jira.commentSend': '전송',
      'jira.createIssue': '이슈 생성',
      'jira.createSummary': '제목',
      'jira.createDesc': '설명',
      'jira.createType': '이슈 유형',
      'jira.creating': '생성 중...',
      'jira.notConfigured': 'Jira가 설정되지 않았습니다. 프로젝트 설정에서 활성화하세요.',
      'jira.assignee': '담당자',
      'jira.unassigned': '미배정',
      'jira.updated': '업데이트',
      'header.jiraTitle': 'Jira 연동',
      'header.jiraBaseUrl': 'Jira URL',
      'header.jiraBaseUrlPlaceholder': 'https://your-domain.atlassian.net',
      'header.jiraProjectKey': '프로젝트 키',
      'header.jiraProjectKeyPlaceholder': '예: PROJ',
      'header.jiraEmail': '이메일',
      'header.jiraEmailPlaceholder': 'your@email.com',
      'header.jiraApiToken': 'API 토큰',
      'header.jiraApiTokenPlaceholder': 'Jira API 토큰',
      'header.jiraTestConnection': '연결 테스트',
      'header.jiraTesting': '테스트 중...',
      'header.jiraConnected': '연결 성공!',
      'header.jiraFailed': '연결 실패',
      'header.jiraTokenHint': 'id.atlassian.com/manage-profile/security/api-tokens에서 토큰을 생성하세요',
    },
  },
};
