import type { ClientPluginManifest } from '../types';
import JiraPanel from '../../components/JiraPanel';
import JiraSettings from './JiraSettings';

export const jiraClientPlugin: ClientPluginManifest = {
  id: 'jira',
  displayName: 'Jira',
  displayNameKo: 'Jira',
  PanelComponent: JiraPanel,
  SettingsComponent: JiraSettings,
  hasTab: true,
  isEnabled: (project) => !!project.jira_enabled,
  translations: {
    en: {
      'tabs.jira': 'Jira',
      'jira.title': 'Jira Issues',
      'jira.search': 'Search issues...',
      'jira.allStatuses': 'All Statuses',
      'jira.refresh': 'Refresh',
      'jira.import': 'Import as Task',
      'jira.importing': 'Importing...',
      'jira.imported': 'Imported!',
      'jira.noIssues': 'No issues found',
      'jira.noIssuesHint': 'Try changing the filter or search query.',
      'jira.loadMore': 'Load More',
      'jira.total': 'total',
      'jira.transition': 'Change Status',
      'jira.comment': 'Comment',
      'jira.commentPlaceholder': 'Add a comment...',
      'jira.commentSend': 'Send',
      'jira.createIssue': 'Create Issue',
      'jira.createSummary': 'Summary',
      'jira.createDesc': 'Description',
      'jira.createType': 'Issue Type',
      'jira.creating': 'Creating...',
      'jira.notConfigured': 'Jira is not configured. Enable it in project settings.',
      'jira.assignee': 'Assignee',
      'jira.unassigned': 'Unassigned',
      'jira.updated': 'Updated',
      'header.jiraTitle': 'Jira Integration',
      'header.jiraBaseUrl': 'Jira URL',
      'header.jiraBaseUrlPlaceholder': 'https://your-domain.atlassian.net',
      'header.jiraProjectKey': 'Project Key',
      'header.jiraProjectKeyPlaceholder': 'e.g. PROJ',
      'header.jiraEmail': 'Email',
      'header.jiraEmailPlaceholder': 'your@email.com',
      'header.jiraApiToken': 'API Token',
      'header.jiraApiTokenPlaceholder': 'Jira API token',
      'header.jiraTestConnection': 'Test Connection',
      'header.jiraTesting': 'Testing...',
      'header.jiraConnected': 'Connected!',
      'header.jiraFailed': 'Connection failed',
      'header.jiraTokenHint': 'Create a token at id.atlassian.com/manage-profile/security/api-tokens',
      'header.jiraDesc': 'Browse Jira issues and import them as AI tasks.',
      'header.jiraGuideToggle': 'Setup Guide',
      'header.jiraGuidePrep': 'Prerequisites',
      'header.jiraGuideStep1': 'Go to id.atlassian.com/manage-profile/security/api-tokens and create an API token',
      'header.jiraGuideStep2': 'Note your Jira URL (e.g. https://your-domain.atlassian.net) and project key (e.g. PROJ)',
      'header.jiraGuideSetup': 'Configuration',
      'header.jiraGuideSetup1': 'Enter Jira URL, project key, email, and API token above',
      'header.jiraGuideSetup2': 'Click "Test Connection" to verify',
      'header.jiraGuideSetup3': 'Save settings',
      'header.jiraGuideUsage': 'Usage',
      'header.jiraGuideUsage1': 'Open the Jira tab in the project detail page',
      'header.jiraGuideUsage2': 'Browse, search, or filter issues by status',
      'header.jiraGuideUsage3': 'Click "Import as Task" to create an AI task from a Jira issue',
    },
    ko: {
      'tabs.jira': 'Jira',
      'jira.title': 'Jira 이슈',
      'jira.search': '이슈 검색...',
      'jira.allStatuses': '모든 상태',
      'jira.refresh': '새로고침',
      'jira.import': '작업으로 가져오기',
      'jira.importing': '가져오는 중...',
      'jira.imported': '가져옴!',
      'jira.noIssues': '이슈가 없습니다',
      'jira.noIssuesHint': '필터나 검색어를 변경해보세요.',
      'jira.loadMore': '더 보기',
      'jira.total': '건',
      'jira.transition': '상태 변경',
      'jira.comment': '댓글',
      'jira.commentPlaceholder': '댓글 입력...',
      'jira.commentSend': '전송',
      'jira.createIssue': '이슈 생성',
      'jira.createSummary': '제목',
      'jira.createDesc': '설명',
      'jira.createType': '이슈 유형',
      'jira.creating': '생성 중...',
      'jira.notConfigured': 'Jira가 설정되지 않았습니다. 프로젝트 설정에서 활성화하세요.',
      'jira.assignee': '담당자',
      'jira.unassigned': '미배정',
      'jira.updated': '업데이트',
      'header.jiraTitle': 'Jira 연동',
      'header.jiraBaseUrl': 'Jira URL',
      'header.jiraBaseUrlPlaceholder': 'https://your-domain.atlassian.net',
      'header.jiraProjectKey': '프로젝트 키',
      'header.jiraProjectKeyPlaceholder': '예: PROJ',
      'header.jiraEmail': '이메일',
      'header.jiraEmailPlaceholder': 'your@email.com',
      'header.jiraApiToken': 'API 토큰',
      'header.jiraApiTokenPlaceholder': 'Jira API 토큰',
      'header.jiraTestConnection': '연결 테스트',
      'header.jiraTesting': '테스트 중...',
      'header.jiraConnected': '연결 성공!',
      'header.jiraFailed': '연결 실패',
      'header.jiraTokenHint': 'id.atlassian.com/manage-profile/security/api-tokens에서 토큰을 생성하세요',
      'header.jiraDesc': 'Jira 이슈를 조회하고 AI 태스크로 가져옵니다.',
      'header.jiraGuideToggle': '설정 가이드',
      'header.jiraGuidePrep': '사전 준비',
      'header.jiraGuideStep1': 'id.atlassian.com/manage-profile/security/api-tokens에서 API 토큰 생성',
      'header.jiraGuideStep2': 'Jira URL (예: https://your-domain.atlassian.net)과 프로젝트 키 (예: PROJ) 확인',
      'header.jiraGuideSetup': '설정 방법',
      'header.jiraGuideSetup1': '위 입력란에 Jira URL, 프로젝트 키, 이메일, API 토큰 입력',
      'header.jiraGuideSetup2': '"연결 테스트" 클릭하여 연결 확인',
      'header.jiraGuideSetup3': '설정 저장',
      'header.jiraGuideUsage': '사용법',
      'header.jiraGuideUsage1': '프로젝트 상세 페이지에서 Jira 탭 진입',
      'header.jiraGuideUsage2': '이슈 검색, 상태 필터링',
      'header.jiraGuideUsage3': '"작업으로 가져오기" 클릭하여 AI 태스크 생성',
    },
  },
};
