import type { ClientPluginManifest } from '../types';
import GitHubPanel from '../../components/GitHubPanel';
import GitHubSettings from './GitHubSettings';

export const githubClientPlugin: ClientPluginManifest = {
  id: 'github',
  displayName: 'GitHub',
  displayNameKo: 'GitHub',
  PanelComponent: GitHubPanel,
  SettingsComponent: GitHubSettings,
  hasTab: true,
  isEnabled: (project) => !!project.github_enabled,
  translations: {
    en: {
      'tabs.github': 'GitHub',
      'github.title': 'GitHub Issues',
      'github.search': 'Search issues...',
      'github.refresh': 'Refresh',
      'github.import': 'Import as Task',
      'github.importing': 'Importing...',
      'github.imported': 'Imported!',
      'github.noIssues': 'No issues found',
      'github.noIssuesHint': 'Try changing the filter or search query.',
      'github.loadMore': 'Load More',
      'github.createIssue': 'Create Issue',
      'github.issueTitle': 'Title',
      'github.issueBody': 'Description',
      'github.creating': 'Creating...',
      'github.notConfigured': 'GitHub is not configured. Enable it in project settings.',
      'github.loadingComments': 'Loading comments...',
      'github.comments': 'Comments',
      'github.noBody': 'No description provided.',
      'github.open': 'Open',
      'github.closed': 'Closed',
      'github.all': 'All',
      'header.githubTitle': 'GitHub Integration',
      'header.githubToken': 'Personal Access Token',
      'header.githubTokenPlaceholder': 'ghp_...',
      'header.githubOwner': 'Owner',
      'header.githubOwnerPlaceholder': 'e.g. octocat',
      'header.githubRepo': 'Repository',
      'header.githubRepoPlaceholder': 'e.g. my-repo',
      'header.githubTestConnection': 'Test Connection',
      'header.githubTesting': 'Testing...',
      'header.githubConnected': 'Connected!',
      'header.githubFailed': 'Connection failed',
      'header.githubTokenHint': 'Create a token at github.com/settings/tokens with repo scope',
    },
    ko: {
      'tabs.github': 'GitHub',
      'github.title': 'GitHub 이슈',
      'github.search': '이슈 검색...',
      'github.refresh': '새로고침',
      'github.import': '작업으로 가져오기',
      'github.importing': '가져오는 중...',
      'github.imported': '가져옴!',
      'github.noIssues': '이슈가 없습니다',
      'github.noIssuesHint': '필터나 검색어를 변경해보세요.',
      'github.loadMore': '더 보기',
      'github.createIssue': '이슈 생성',
      'github.issueTitle': '제목',
      'github.issueBody': '설명',
      'github.creating': '생성 중...',
      'github.notConfigured': 'GitHub이 설정되지 않았습니다. 프로젝트 설정에서 활성화하세요.',
      'github.loadingComments': '댓글 로딩 중...',
      'github.comments': '댓글',
      'github.noBody': '설명이 없습니다.',
      'github.open': '열림',
      'github.closed': '닫힘',
      'github.all': '전체',
      'header.githubTitle': 'GitHub 연동',
      'header.githubToken': '개인 액세스 토큰',
      'header.githubTokenPlaceholder': 'ghp_...',
      'header.githubOwner': '소유자',
      'header.githubOwnerPlaceholder': '예: octocat',
      'header.githubRepo': '저장소',
      'header.githubRepoPlaceholder': '예: my-repo',
      'header.githubTestConnection': '연결 테스트',
      'header.githubTesting': '테스트 중...',
      'header.githubConnected': '연결 성공!',
      'header.githubFailed': '연결 실패',
      'header.githubTokenHint': 'github.com/settings/tokens에서 repo 권한으로 토큰을 생성하세요',
    },
  },
};
