import type { ClientPluginManifest } from '../types';
import GitHubPanel from '../../components/GitHubPanel';
import GitHubSettings from './GitHubSettings';

export const githubClientPlugin: ClientPluginManifest = {
  id: 'github',
  displayName: 'GitHub',
  displayNameKo: 'GitHub',
  PanelComponent: GitHubPanel,
  SettingsComponent: GitHubSettings,
  hasTab: true,
  isEnabled: (project) => !!project.github_enabled,
  translations: {
    en: {
      'tabs.github': 'GitHub',
      'github.title': 'GitHub Issues',
      'github.search': 'Search issues...',
      'github.refresh': 'Refresh',
      'github.import': 'Import as Task',
      'github.importing': 'Importing...',
      'github.imported': 'Imported!',
      'github.noIssues': 'No issues found',
      'github.noIssuesHint': 'Try changing the filter or search query.',
      'github.loadMore': 'Load More',
      'github.createIssue': 'Create Issue',
      'github.issueTitle': 'Title',
      'github.issueBody': 'Description',
      'github.creating': 'Creating...',
      'github.notConfigured': 'GitHub is not configured. Enable it in project settings.',
      'github.loadingComments': 'Loading comments...',
      'github.comments': 'Comments',
      'github.noBody': 'No description provided.',
      'github.open': 'Open',
      'github.closed': 'Closed',
      'github.all': 'All',
      'header.githubTitle': 'GitHub Integration',
      'header.githubToken': 'Personal Access Token',
      'header.githubTokenPlaceholder': 'ghp_...',
      'header.githubOwner': 'Owner',
      'header.githubOwnerPlaceholder': 'e.g. octocat',
      'header.githubRepo': 'Repository',
      'header.githubRepoPlaceholder': 'e.g. my-repo',
      'header.githubTestConnection': 'Test Connection',
      'header.githubTesting': 'Testing...',
      'header.githubConnected': 'Connected!',
      'header.githubFailed': 'Connection failed',
      'header.githubTokenHint': 'Create a token at github.com/settings/tokens with repo scope',
      'header.githubDesc': 'Browse GitHub issues and import them as AI tasks.',
      'header.githubGuideToggle': 'Setup Guide',
      'header.githubGuidePrep': 'Prerequisites',
      'header.githubGuideStep1': 'Go to github.com/settings/tokens and create a Personal Access Token with "repo" scope',
      'header.githubGuideStep2': 'Note the repository owner (e.g. octocat) and name (e.g. my-repo)',
      'header.githubGuideSetup': 'Configuration',
      'header.githubGuideSetup1': 'Enter the token, owner, and repository name above',
      'header.githubGuideSetup2': 'Click "Test Connection" to verify',
      'header.githubGuideSetup3': 'Save settings',
      'header.githubGuideUsage': 'Usage',
      'header.githubGuideUsage1': 'Open the GitHub tab in the project detail page',
      'header.githubGuideUsage2': 'Browse issues, filter by state (open/closed), or search',
      'header.githubGuideUsage3': 'Click "Import as Task" to create an AI task from an issue',
    },
    ko: {
      'tabs.github': 'GitHub',
      'github.title': 'GitHub 이슈',
      'github.search': '이슈 검색...',
      'github.refresh': '새로고침',
      'github.import': '작업으로 가져오기',
      'github.importing': '가져오는 중...',
      'github.imported': '가져옴!',
      'github.noIssues': '이슈가 없습니다',
      'github.noIssuesHint': '필터나 검색어를 변경해보세요.',
      'github.loadMore': '더 보기',
      'github.createIssue': '이슈 생성',
      'github.issueTitle': '제목',
      'github.issueBody': '설명',
      'github.creating': '생성 중...',
      'github.notConfigured': 'GitHub이 설정되지 않았습니다. 프로젝트 설정에서 활성화하세요.',
      'github.loadingComments': '댓글 로딩 중...',
      'github.comments': '댓글',
      'github.noBody': '설명이 없습니다.',
      'github.open': '열림',
      'github.closed': '닫힘',
      'github.all': '전체',
      'header.githubTitle': 'GitHub 연동',
      'header.githubToken': '개인 액세스 토큰',
      'header.githubTokenPlaceholder': 'ghp_...',
      'header.githubOwner': '소유자',
      'header.githubOwnerPlaceholder': '예: octocat',
      'header.githubRepo': '저장소',
      'header.githubRepoPlaceholder': '예: my-repo',
      'header.githubTestConnection': '연결 테스트',
      'header.githubTesting': '테스트 중...',
      'header.githubConnected': '연결 성공!',
      'header.githubFailed': '연결 실패',
      'header.githubTokenHint': 'github.com/settings/tokens에서 repo 권한으로 토큰을 생성하세요',
      'header.githubDesc': 'GitHub 이슈를 조회하고 AI 태스크로 가져옵니다.',
      'header.githubGuideToggle': '설정 가이드',
      'header.githubGuidePrep': '사전 준비',
      'header.githubGuideStep1': 'github.com/settings/tokens에서 "repo" 권한의 Personal Access Token 생성',
      'header.githubGuideStep2': '레포지토리 소유자 (예: octocat)와 이름 (예: my-repo) 확인',
      'header.githubGuideSetup': '설정 방법',
      'header.githubGuideSetup1': '위 입력란에 토큰, 소유자, 저장소 이름 입력',
      'header.githubGuideSetup2': '"연결 테스트" 클릭하여 연결 확인',
      'header.githubGuideSetup3': '설정 저장',
      'header.githubGuideUsage': '사용법',
      'header.githubGuideUsage1': '프로젝트 상세 페이지에서 GitHub 탭 진입',
      'header.githubGuideUsage2': '이슈 검색, open/closed 필터링',
      'header.githubGuideUsage3': '"작업으로 가져오기" 클릭하여 AI 태스크 생성',
    },
  },
};
