import type { ClientPluginManifest } from '../types';
import NotionPanel from '../../components/NotionPanel';
import NotionSettings from './NotionSettings';

export const notionClientPlugin: ClientPluginManifest = {
  id: 'notion',
  displayName: 'Notion',
  displayNameKo: 'Notion',
  PanelComponent: NotionPanel,
  SettingsComponent: NotionSettings,
  hasTab: true,
  isEnabled: (project) => !!project.notion_enabled,
  translations: {
    en: {
      'tabs.notion': 'Notion',
      'notion.title': 'Notion Pages',
      'notion.search': 'Search pages...',
      'notion.refresh': 'Refresh',
      'notion.import': 'Import as Task',
      'notion.importing': 'Importing...',
      'notion.imported': 'Imported!',
      'notion.noPages': 'No pages found',
      'notion.noPagesHint': 'Try changing the search query.',
      'notion.loadMore': 'Load More',
      'notion.createPage': 'Create Page',
      'notion.pageTitle': 'Title',
      'notion.creating': 'Creating...',
      'notion.notConfigured': 'Notion is not configured. Enable it in project settings.',
      'notion.loadingContent': 'Loading content...',
      'notion.noContent': 'No content',
      'header.notionTitle': 'Notion Integration',
      'header.notionApiKey': 'Integration Token',
      'header.notionApiKeyPlaceholder': 'secret_...',
      'header.notionDatabaseId': 'Database ID',
      'header.notionDatabaseIdPlaceholder': '32-char hex ID from database URL',
      'header.notionTestConnection': 'Test Connection',
      'header.notionTesting': 'Testing...',
      'header.notionConnected': 'Connected!',
      'header.notionFailed': 'Connection failed',
      'header.notionTokenHint': 'Create an integration at notion.so/my-integrations and share the database with it',
      'header.notionDesc': 'Browse Notion pages and import them as AI tasks.',
      'header.notionGuideToggle': 'Setup Guide',
      'header.notionGuidePrep': 'Prerequisites',
      'header.notionGuideStep1': 'Go to notion.so/my-integrations and create an Integration — copy the API key',
      'header.notionGuideStep2': 'Open your Notion database page, click "..." > Connections > select the Integration',
      'header.notionGuideStep3': 'Copy the Database ID from the URL (32-char hex string before "?v=")',
      'header.notionGuideSetup': 'Configuration',
      'header.notionGuideSetup1': 'Enter the API key and Database ID above',
      'header.notionGuideSetup2': 'Click "Test Connection" to verify',
      'header.notionGuideSetup3': 'Save settings',
      'header.notionGuideUsage': 'Usage',
      'header.notionGuideUsage1': 'Open the Notion tab in the project detail page',
      'header.notionGuideUsage2': 'Browse pages, search by title, view block content',
      'header.notionGuideUsage3': 'Click "Import as Task" to create an AI task from a page',
    },
    ko: {
      'tabs.notion': 'Notion',
      'notion.title': 'Notion 페이지',
      'notion.search': '페이지 검색...',
      'notion.refresh': '새로고침',
      'notion.import': '작업으로 가져오기',
      'notion.importing': '가져오는 중...',
      'notion.imported': '가져옴!',
      'notion.noPages': '페이지가 없습니다',
      'notion.noPagesHint': '검색어를 변경해보세요.',
      'notion.loadMore': '더 보기',
      'notion.createPage': '페이지 생성',
      'notion.pageTitle': '제목',
      'notion.creating': '생성 중...',
      'notion.notConfigured': 'Notion이 설정되지 않았습니다. 프로젝트 설정에서 활성화하세요.',
      'notion.loadingContent': '콘텐츠 로딩 중...',
      'notion.noContent': '콘텐츠 없음',
      'header.notionTitle': 'Notion 연동',
      'header.notionApiKey': '통합 토큰',
      'header.notionApiKeyPlaceholder': 'secret_...',
      'header.notionDatabaseId': '데이터베이스 ID',
      'header.notionDatabaseIdPlaceholder': '데이터베이스 URL의 32자 hex ID',
      'header.notionTestConnection': '연결 테스트',
      'header.notionTesting': '테스트 중...',
      'header.notionConnected': '연결 성공!',
      'header.notionFailed': '연결 실패',
      'header.notionTokenHint': 'notion.so/my-integrations에서 통합을 생성하고 데이터베이스를 공유하세요',
      'header.notionDesc': 'Notion 페이지를 조회하고 AI 태스크로 가져옵니다.',
      'header.notionGuideToggle': '설정 가이드',
      'header.notionGuidePrep': '사전 준비',
      'header.notionGuideStep1': 'notion.so/my-integrations에서 Integration 생성 → API 키 복사',
      'header.notionGuideStep2': 'Notion 데이터베이스 페이지 → "..." → 연결 → 생성한 Integration 선택',
      'header.notionGuideStep3': '데이터베이스 URL에서 Database ID 복사 ("?v=" 앞의 32자리 hex)',
      'header.notionGuideSetup': '설정 방법',
      'header.notionGuideSetup1': '위 입력란에 API 키와 Database ID 입력',
      'header.notionGuideSetup2': '"연결 테스트" 클릭하여 연결 확인',
      'header.notionGuideSetup3': '설정 저장',
      'header.notionGuideUsage': '사용법',
      'header.notionGuideUsage1': '프로젝트 상세 페이지에서 Notion 탭 진입',
      'header.notionGuideUsage2': '페이지 검색, 블록 콘텐츠 확인',
      'header.notionGuideUsage3': '"작업으로 가져오기" 클릭하여 AI 태스크 생성',
    },
  },
};
